---
name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        php-version: [8.5]

    steps:
      - uses: actions/checkout@v7

      - name: Use Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, mbstring, simplexml
        env: { fail-fast: true }

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v4

      - name: Lint code
        run: vp run lint
