---
name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4]

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v5

      - name: Use Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
        env: { fail-fast: true }

      - name: Cache Composer packages
        uses: actions/cache@v4
        env: { cache-name: composer }
        with:
          path: vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint-${{ env.cache-name }}-
            ${{ runner.os }}-lint-
            ${{ runner.os }}-

      - name: Install Composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Lint code
        run: vp run lint
