---
name: Test

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4]

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
        env: { fail-fast: true }

      - name: Cache Composer packages
        uses: actions/cache@v3
        env: { cache-name: composer }
        with:
          path: vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Install Composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Test code
        run: vendor/bin/phpunit --configuration phpunit.xml
